# Generated by Django 3.2.11 on 2022-01-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=4, max_digits=6)),
                ('link', models.URLField()),
                ('place', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.URLField()),
                ('cast', models.CharField(help_text='Introduzca nombres separados por comas', max_length=250)),
            ],
        ),
    ]
