# Generated by Django 3.2.11 on 2022-03-01 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('peliculas', '0006_coichesindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoichesIndexPage',
            new_name='CochesIndexPage',
        ),
    ]
