# Generated by Django 4.0.3 on 2022-03-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_cochepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coche',
            options={'verbose_name_plural': 'coches'},
        ),
        migrations.DeleteModel(
            name='CochePage',
        ),
    ]
